modLoader="javafml"
loaderVersion="[45,)"
license="Public Domain"

[[mods]]
modId="bussounds"
version="1"
displayName="BusSounds"
credits="The sounds mod for Minecraft Bus Project !"
displayURL="https://github.com/BlocBlocTheBloc0/MinecraftBus"
authors="BlocBlocTheBloc"
description="The sounds mod of the project"

[[dependencies.bussounds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.bussounds]]
    modId="busverif"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


