
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.blocblocthebloc.bussounds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import fr.blocblocthebloc.bussounds.block.ViticulBlock;
import fr.blocblocthebloc.bussounds.block.VertiBlock;
import fr.blocblocthebloc.bussounds.block.UseBlock;
import fr.blocblocthebloc.bussounds.block.UniversiteBlock;
import fr.blocblocthebloc.bussounds.block.TunesBlock;
import fr.blocblocthebloc.bussounds.block.TroubadourBlock;
import fr.blocblocthebloc.bussounds.block.TridentBlock;
import fr.blocblocthebloc.bussounds.block.TheoBlock;
import fr.blocblocthebloc.bussounds.block.ThelayBlock;
import fr.blocblocthebloc.bussounds.block.TheatreBlock;
import fr.blocblocthebloc.bussounds.block.TeteduBlock;
import fr.blocblocthebloc.bussounds.block.TailsBlock;
import fr.blocblocthebloc.bussounds.block.SurcoteBlock;
import fr.blocblocthebloc.bussounds.block.StarlessBlock;
import fr.blocblocthebloc.bussounds.block.StPoulinBlock;
import fr.blocblocthebloc.bussounds.block.SouscoteBlock;
import fr.blocblocthebloc.bussounds.block.SourcesBlock;
import fr.blocblocthebloc.bussounds.block.SoufflerieBlock;
import fr.blocblocthebloc.bussounds.block.SoleilBlock;
import fr.blocblocthebloc.bussounds.block.SogzitBlock;
import fr.blocblocthebloc.bussounds.block.Sep1Block;
import fr.blocblocthebloc.bussounds.block.SansBlock;
import fr.blocblocthebloc.bussounds.block.SamrutoBlock;
import fr.blocblocthebloc.bussounds.block.SabrinaBlock;
import fr.blocblocthebloc.bussounds.block.RueBlock;
import fr.blocblocthebloc.bussounds.block.RoustBlock;
import fr.blocblocthebloc.bussounds.block.RouloniBlock;
import fr.blocblocthebloc.bussounds.block.RoudinBlock;
import fr.blocblocthebloc.bussounds.block.RomainsBlock;
import fr.blocblocthebloc.bussounds.block.RolandBlock;
import fr.blocblocthebloc.bussounds.block.RestaurationBlock;
import fr.blocblocthebloc.bussounds.block.ResidanceNTBlock;
import fr.blocblocthebloc.bussounds.block.ResidanceBlock;
import fr.blocblocthebloc.bussounds.block.RenarBlock;
import fr.blocblocthebloc.bussounds.block.RailsBlock;
import fr.blocblocthebloc.bussounds.block.PresBulonBlock;
import fr.blocblocthebloc.bussounds.block.PotageBlock;
import fr.blocblocthebloc.bussounds.block.PorteauboisBlock;
import fr.blocblocthebloc.bussounds.block.PontdelaubeNTBlock;
import fr.blocblocthebloc.bussounds.block.PontdelaubeBlock;
import fr.blocblocthebloc.bussounds.block.PontdelairBlock;
import fr.blocblocthebloc.bussounds.block.PontdeauBlock;
import fr.blocblocthebloc.bussounds.block.PointRondBlock;
import fr.blocblocthebloc.bussounds.block.PointBronzeBlock;
import fr.blocblocthebloc.bussounds.block.PlaceCampagneBlock;
import fr.blocblocthebloc.bussounds.block.PigmentBlock;
import fr.blocblocthebloc.bussounds.block.PassageBlock;
import fr.blocblocthebloc.bussounds.block.ParviBlock;
import fr.blocblocthebloc.bussounds.block.ParsolonaBlock;
import fr.blocblocthebloc.bussounds.block.ParcLogistiqueBlock;
import fr.blocblocthebloc.bussounds.block.ParcCommunBlock;
import fr.blocblocthebloc.bussounds.block.PaixBlock;
import fr.blocblocthebloc.bussounds.block.PainBlock;
import fr.blocblocthebloc.bussounds.block.OutilsBlock;
import fr.blocblocthebloc.bussounds.block.OrientalBlock;
import fr.blocblocthebloc.bussounds.block.OlmarBlock;
import fr.blocblocthebloc.bussounds.block.NuancesBlock;
import fr.blocblocthebloc.bussounds.block.Nov11Block;
import fr.blocblocthebloc.bussounds.block.NordBlock;
import fr.blocblocthebloc.bussounds.block.NagiBlock;
import fr.blocblocthebloc.bussounds.block.MontBlock;
import fr.blocblocthebloc.bussounds.block.MaternelBlock;
import fr.blocblocthebloc.bussounds.block.MasteurBlock;
import fr.blocblocthebloc.bussounds.block.MartreBlock;
import fr.blocblocthebloc.bussounds.block.MarcheBlock;
import fr.blocblocthebloc.bussounds.block.ManiaBlock;
import fr.blocblocthebloc.bussounds.block.MaisBlock;
import fr.blocblocthebloc.bussounds.block.Mais1Block;
import fr.blocblocthebloc.bussounds.block.MairieBlock;
import fr.blocblocthebloc.bussounds.block.MagasinsUsineNTBlock;
import fr.blocblocthebloc.bussounds.block.MagasinsUsineBlock;
import fr.blocblocthebloc.bussounds.block.LumiereBlock;
import fr.blocblocthebloc.bussounds.block.LuenBlock;
import fr.blocblocthebloc.bussounds.block.LouisBlock;
import fr.blocblocthebloc.bussounds.block.LogeBlock;
import fr.blocblocthebloc.bussounds.block.LitieumBlock;
import fr.blocblocthebloc.bussounds.block.LithyaBlock;
import fr.blocblocthebloc.bussounds.block.LeguerrierBlock;
import fr.blocblocthebloc.bussounds.block.LamcombreBlock;
import fr.blocblocthebloc.bussounds.block.LacanaileBlock;
import fr.blocblocthebloc.bussounds.block.KyouBlock;
import fr.blocblocthebloc.bussounds.block.KiroBlock;
import fr.blocblocthebloc.bussounds.block.Jui14Block;
import fr.blocblocthebloc.bussounds.block.JardinsdelaGareBlock;
import fr.blocblocthebloc.bussounds.block.Jan1Block;
import fr.blocblocthebloc.bussounds.block.IleBlock;
import fr.blocblocthebloc.bussounds.block.HumbourgeurBlock;
import fr.blocblocthebloc.bussounds.block.HopitalBlock;
import fr.blocblocthebloc.bussounds.block.HakimBlock;
import fr.blocblocthebloc.bussounds.block.HabitacleBlock;
import fr.blocblocthebloc.bussounds.block.GareCentraleBlock;
import fr.blocblocthebloc.bussounds.block.GareBlock;
import fr.blocblocthebloc.bussounds.block.FrankBlock;
import fr.blocblocthebloc.bussounds.block.FontaineBlock;
import fr.blocblocthebloc.bussounds.block.FlochBlock;
import fr.blocblocthebloc.bussounds.block.FlaureteBlock;
import fr.blocblocthebloc.bussounds.block.FiouseBlock;
import fr.blocblocthebloc.bussounds.block.FeuwarBlock;
import fr.blocblocthebloc.bussounds.block.FeuBBlock;
import fr.blocblocthebloc.bussounds.block.Feb29Block;
import fr.blocblocthebloc.bussounds.block.Feb21Block;
import fr.blocblocthebloc.bussounds.block.EteBlock;
import fr.blocblocthebloc.bussounds.block.ElementoBlock;
import fr.blocblocthebloc.bussounds.block.EduicoBlock;
import fr.blocblocthebloc.bussounds.block.EcolesNTBlock;
import fr.blocblocthebloc.bussounds.block.EcolesBlock;
import fr.blocblocthebloc.bussounds.block.DurianBlock;
import fr.blocblocthebloc.bussounds.block.DucartonBlock;
import fr.blocblocthebloc.bussounds.block.DuboulangeBlock;
import fr.blocblocthebloc.bussounds.block.DemiCielBlock;
import fr.blocblocthebloc.bussounds.block.DelacourBlock;
import fr.blocblocthebloc.bussounds.block.DegantBlock;
import fr.blocblocthebloc.bussounds.block.DecolorBlock;
import fr.blocblocthebloc.bussounds.block.DachanBlock;
import fr.blocblocthebloc.bussounds.block.CrytalineBlock;
import fr.blocblocthebloc.bussounds.block.CorpsBlock;
import fr.blocblocthebloc.bussounds.block.CollegeStDemainBlock;
import fr.blocblocthebloc.bussounds.block.CoeurBlock;
import fr.blocblocthebloc.bussounds.block.CliniqueBlock;
import fr.blocblocthebloc.bussounds.block.CimetiereBlock;
import fr.blocblocthebloc.bussounds.block.ChemineeBlock;
import fr.blocblocthebloc.bussounds.block.CheminBlock;
import fr.blocblocthebloc.bussounds.block.CharmauxBlock;
import fr.blocblocthebloc.bussounds.block.CharbBlock;
import fr.blocblocthebloc.bussounds.block.ChantsBlock;
import fr.blocblocthebloc.bussounds.block.ChampsdedaviBlock;
import fr.blocblocthebloc.bussounds.block.ChampsDeBleBlock;
import fr.blocblocthebloc.bussounds.block.ChamponaisBlock;
import fr.blocblocthebloc.bussounds.block.CentreVilleBlock;
import fr.blocblocthebloc.bussounds.block.CentreLogistiqueBlock;
import fr.blocblocthebloc.bussounds.block.CentreCommercialBlock;
import fr.blocblocthebloc.bussounds.block.CentreAdministratifBlock;
import fr.blocblocthebloc.bussounds.block.CastadreamBlock;
import fr.blocblocthebloc.bussounds.block.CampusBlock;
import fr.blocblocthebloc.bussounds.block.CampagneBlock;
import fr.blocblocthebloc.bussounds.block.CalamardeBlock;
import fr.blocblocthebloc.bussounds.block.BulonBlock;
import fr.blocblocthebloc.bussounds.block.BourseBlock;
import fr.blocblocthebloc.bussounds.block.BanletaBlock;
import fr.blocblocthebloc.bussounds.block.AurelienBlock;
import fr.blocblocthebloc.bussounds.block.ArmageddonBlock;
import fr.blocblocthebloc.bussounds.block.AppartementBlock;
import fr.blocblocthebloc.bussounds.block.AncienneGareBlock;
import fr.blocblocthebloc.bussounds.block.AnBlock;
import fr.blocblocthebloc.bussounds.block.AbbyBlock;
import fr.blocblocthebloc.bussounds.BussoundsMod;

public class BussoundsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, BussoundsMod.MODID);
	public static final RegistryObject<Block> PLACE_CAMPAGNE = REGISTRY.register("place_campagne", () -> new PlaceCampagneBlock());
	public static final RegistryObject<Block> CHAMPS_DE_BLE = REGISTRY.register("champs_de_ble", () -> new ChampsDeBleBlock());
	public static final RegistryObject<Block> SOGZIT = REGISTRY.register("sogzit", () -> new SogzitBlock());
	public static final RegistryObject<Block> PAIN = REGISTRY.register("pain", () -> new PainBlock());
	public static final RegistryObject<Block> FEB_21 = REGISTRY.register("feb_21", () -> new Feb21Block());
	public static final RegistryObject<Block> PARC_COMMUN = REGISTRY.register("parc_commun", () -> new ParcCommunBlock());
	public static final RegistryObject<Block> ROUST = REGISTRY.register("roust", () -> new RoustBlock());
	public static final RegistryObject<Block> POINT_BRONZE = REGISTRY.register("point_bronze", () -> new PointBronzeBlock());
	public static final RegistryObject<Block> CENTRE_VILLE = REGISTRY.register("centre_ville", () -> new CentreVilleBlock());
	public static final RegistryObject<Block> GARE = REGISTRY.register("gare", () -> new GareBlock());
	public static final RegistryObject<Block> CASTADREAM = REGISTRY.register("castadream", () -> new CastadreamBlock());
	public static final RegistryObject<Block> FEB_29 = REGISTRY.register("feb_29", () -> new Feb29Block());
	public static final RegistryObject<Block> LITIEUM = REGISTRY.register("litieum", () -> new LitieumBlock());
	public static final RegistryObject<Block> FRANK = REGISTRY.register("frank", () -> new FrankBlock());
	public static final RegistryObject<Block> ABBY = REGISTRY.register("abby", () -> new AbbyBlock());
	public static final RegistryObject<Block> DECOLOR = REGISTRY.register("decolor", () -> new DecolorBlock());
	public static final RegistryObject<Block> ROLAND = REGISTRY.register("roland", () -> new RolandBlock());
	public static final RegistryObject<Block> CENTRE_LOGISTIQUE = REGISTRY.register("centre_logistique", () -> new CentreLogistiqueBlock());
	public static final RegistryObject<Block> ILE = REGISTRY.register("ile", () -> new IleBlock());
	public static final RegistryObject<Block> FEUWAR = REGISTRY.register("feuwar", () -> new FeuwarBlock());
	public static final RegistryObject<Block> RAILS = REGISTRY.register("rails", () -> new RailsBlock());
	public static final RegistryObject<Block> CIMETIERE = REGISTRY.register("cimetiere", () -> new CimetiereBlock());
	public static final RegistryObject<Block> RUE = REGISTRY.register("rue", () -> new RueBlock());
	public static final RegistryObject<Block> NOV_11 = REGISTRY.register("nov_11", () -> new Nov11Block());
	public static final RegistryObject<Block> CAMPAGNE = REGISTRY.register("campagne", () -> new CampagneBlock());
	public static final RegistryObject<Block> FONTAINE = REGISTRY.register("fontaine", () -> new FontaineBlock());
	public static final RegistryObject<Block> CHARMAUX = REGISTRY.register("charmaux", () -> new CharmauxBlock());
	public static final RegistryObject<Block> PONTDEAU = REGISTRY.register("pontdeau", () -> new PontdeauBlock());
	public static final RegistryObject<Block> FLAURETE = REGISTRY.register("flaurete", () -> new FlaureteBlock());
	public static final RegistryObject<Block> DURIAN = REGISTRY.register("durian", () -> new DurianBlock());
	public static final RegistryObject<Block> TROUBADOUR = REGISTRY.register("troubadour", () -> new TroubadourBlock());
	public static final RegistryObject<Block> ST_POULIN = REGISTRY.register("st_poulin", () -> new StPoulinBlock());
	public static final RegistryObject<Block> EDUICO = REGISTRY.register("eduico", () -> new EduicoBlock());
	public static final RegistryObject<Block> MAIS_1 = REGISTRY.register("mais_1", () -> new Mais1Block());
	public static final RegistryObject<Block> THEATRE = REGISTRY.register("theatre", () -> new TheatreBlock());
	public static final RegistryObject<Block> VITICUL = REGISTRY.register("viticul", () -> new ViticulBlock());
	public static final RegistryObject<Block> OUTILS = REGISTRY.register("outils", () -> new OutilsBlock());
	public static final RegistryObject<Block> NUANCES = REGISTRY.register("nuances", () -> new NuancesBlock());
	public static final RegistryObject<Block> POINT_ROND = REGISTRY.register("point_rond", () -> new PointRondBlock());
	public static final RegistryObject<Block> SANS = REGISTRY.register("sans", () -> new SansBlock());
	public static final RegistryObject<Block> CORPS = REGISTRY.register("corps", () -> new CorpsBlock());
	public static final RegistryObject<Block> JUI_14 = REGISTRY.register("jui_14", () -> new Jui14Block());
	public static final RegistryObject<Block> LEGUERRIER = REGISTRY.register("leguerrier", () -> new LeguerrierBlock());
	public static final RegistryObject<Block> RESIDANCE = REGISTRY.register("residance", () -> new ResidanceBlock());
	public static final RegistryObject<Block> RENAR = REGISTRY.register("renar", () -> new RenarBlock());
	public static final RegistryObject<Block> SOURCES = REGISTRY.register("sources", () -> new SourcesBlock());
	public static final RegistryObject<Block> ROMAINS = REGISTRY.register("romains", () -> new RomainsBlock());
	public static final RegistryObject<Block> FEU_B = REGISTRY.register("feu_b", () -> new FeuBBlock());
	public static final RegistryObject<Block> JAN_1 = REGISTRY.register("jan_1", () -> new Jan1Block());
	public static final RegistryObject<Block> RESTAURATION = REGISTRY.register("restauration", () -> new RestaurationBlock());
	public static final RegistryObject<Block> MARCHE = REGISTRY.register("marche", () -> new MarcheBlock());
	public static final RegistryObject<Block> THEO = REGISTRY.register("theo", () -> new TheoBlock());
	public static final RegistryObject<Block> ROUDIN = REGISTRY.register("roudin", () -> new RoudinBlock());
	public static final RegistryObject<Block> CENTRE_ADMINISTRATIF = REGISTRY.register("centre_administratif", () -> new CentreAdministratifBlock());
	public static final RegistryObject<Block> CHEMIN = REGISTRY.register("chemin", () -> new CheminBlock());
	public static final RegistryObject<Block> DELACOUR = REGISTRY.register("delacour", () -> new DelacourBlock());
	public static final RegistryObject<Block> MANIA = REGISTRY.register("mania", () -> new ManiaBlock());
	public static final RegistryObject<Block> MAIS = REGISTRY.register("mais", () -> new MaisBlock());
	public static final RegistryObject<Block> DUCARTON = REGISTRY.register("ducarton", () -> new DucartonBlock());
	public static final RegistryObject<Block> TUNES = REGISTRY.register("tunes", () -> new TunesBlock());
	public static final RegistryObject<Block> HOPITAL = REGISTRY.register("hopital", () -> new HopitalBlock());
	public static final RegistryObject<Block> LAMCOMBRE = REGISTRY.register("lamcombre", () -> new LamcombreBlock());
	public static final RegistryObject<Block> LACANAILE = REGISTRY.register("lacanaile", () -> new LacanaileBlock());
	public static final RegistryObject<Block> ANCIENNE_GARE = REGISTRY.register("ancienne_gare", () -> new AncienneGareBlock());
	public static final RegistryObject<Block> CLINIQUE = REGISTRY.register("clinique", () -> new CliniqueBlock());
	public static final RegistryObject<Block> APPARTEMENT = REGISTRY.register("appartement", () -> new AppartementBlock());
	public static final RegistryObject<Block> AURELIEN = REGISTRY.register("aurelien", () -> new AurelienBlock());
	public static final RegistryObject<Block> USE = REGISTRY.register("use", () -> new UseBlock());
	public static final RegistryObject<Block> SURCOTE = REGISTRY.register("surcote", () -> new SurcoteBlock());
	public static final RegistryObject<Block> PIGMENT = REGISTRY.register("pigment", () -> new PigmentBlock());
	public static final RegistryObject<Block> POTAGE = REGISTRY.register("potage", () -> new PotageBlock());
	public static final RegistryObject<Block> DUBOULANGE = REGISTRY.register("duboulange", () -> new DuboulangeBlock());
	public static final RegistryObject<Block> ETE = REGISTRY.register("ete", () -> new EteBlock());
	public static final RegistryObject<Block> MAGASINS_USINE = REGISTRY.register("magasins_usine", () -> new MagasinsUsineBlock());
	public static final RegistryObject<Block> CENTRE_COMMERCIAL = REGISTRY.register("centre_commercial", () -> new CentreCommercialBlock());
	public static final RegistryObject<Block> THELAY = REGISTRY.register("thelay", () -> new ThelayBlock());
	public static final RegistryObject<Block> OLMAR = REGISTRY.register("olmar", () -> new OlmarBlock());
	public static final RegistryObject<Block> BOURSE = REGISTRY.register("bourse", () -> new BourseBlock());
	public static final RegistryObject<Block> LOUIS = REGISTRY.register("louis", () -> new LouisBlock());
	public static final RegistryObject<Block> PARVI = REGISTRY.register("parvi", () -> new ParviBlock());
	public static final RegistryObject<Block> DEGANT = REGISTRY.register("degant", () -> new DegantBlock());
	public static final RegistryObject<Block> PASSAGE = REGISTRY.register("passage", () -> new PassageBlock());
	public static final RegistryObject<Block> NAGI = REGISTRY.register("nagi", () -> new NagiBlock());
	public static final RegistryObject<Block> COEUR = REGISTRY.register("coeur", () -> new CoeurBlock());
	public static final RegistryObject<Block> PAIX = REGISTRY.register("paix", () -> new PaixBlock());
	public static final RegistryObject<Block> CHARB = REGISTRY.register("charb", () -> new CharbBlock());
	public static final RegistryObject<Block> LOGE = REGISTRY.register("loge", () -> new LogeBlock());
	public static final RegistryObject<Block> COLLEGE_ST_DEMAIN = REGISTRY.register("college_st_demain", () -> new CollegeStDemainBlock());
	public static final RegistryObject<Block> KIRO = REGISTRY.register("kiro", () -> new KiroBlock());
	public static final RegistryObject<Block> UNIVERSITE = REGISTRY.register("universite", () -> new UniversiteBlock());
	public static final RegistryObject<Block> CAMPUS = REGISTRY.register("campus", () -> new CampusBlock());
	public static final RegistryObject<Block> ECOLES = REGISTRY.register("ecoles", () -> new EcolesBlock());
	public static final RegistryObject<Block> CHANTS = REGISTRY.register("chants", () -> new ChantsBlock());
	public static final RegistryObject<Block> VERTI = REGISTRY.register("verti", () -> new VertiBlock());
	public static final RegistryObject<Block> MARTRE = REGISTRY.register("martre", () -> new MartreBlock());
	public static final RegistryObject<Block> LITHYA = REGISTRY.register("lithya", () -> new LithyaBlock());
	public static final RegistryObject<Block> SOLEIL = REGISTRY.register("soleil", () -> new SoleilBlock());
	public static final RegistryObject<Block> SOUSCOTE = REGISTRY.register("souscote", () -> new SouscoteBlock());
	public static final RegistryObject<Block> ELEMENTO = REGISTRY.register("elemento", () -> new ElementoBlock());
	public static final RegistryObject<Block> PONTDELAUBE = REGISTRY.register("pontdelaube", () -> new PontdelaubeBlock());
	public static final RegistryObject<Block> BULON = REGISTRY.register("bulon", () -> new BulonBlock());
	public static final RegistryObject<Block> HABITACLE = REGISTRY.register("habitacle", () -> new HabitacleBlock());
	public static final RegistryObject<Block> LUEN = REGISTRY.register("luen", () -> new LuenBlock());
	public static final RegistryObject<Block> HAKIM = REGISTRY.register("hakim", () -> new HakimBlock());
	public static final RegistryObject<Block> SOUFFLERIE = REGISTRY.register("soufflerie", () -> new SoufflerieBlock());
	public static final RegistryObject<Block> CALAMARDE = REGISTRY.register("calamarde", () -> new CalamardeBlock());
	public static final RegistryObject<Block> PARC_LOGISTIQUE = REGISTRY.register("parc_logistique", () -> new ParcLogistiqueBlock());
	public static final RegistryObject<Block> TAILS = REGISTRY.register("tails", () -> new TailsBlock());
	public static final RegistryObject<Block> PONTDELAIR = REGISTRY.register("pontdelair", () -> new PontdelairBlock());
	public static final RegistryObject<Block> JARDINSDELA_GARE = REGISTRY.register("jardinsdela_gare", () -> new JardinsdelaGareBlock());
	public static final RegistryObject<Block> GARE_CENTRALE = REGISTRY.register("gare_centrale", () -> new GareCentraleBlock());
	public static final RegistryObject<Block> MAIRIE = REGISTRY.register("mairie", () -> new MairieBlock());
	public static final RegistryObject<Block> ROULONI = REGISTRY.register("rouloni", () -> new RouloniBlock());
	public static final RegistryObject<Block> SEP_1 = REGISTRY.register("sep_1", () -> new Sep1Block());
	public static final RegistryObject<Block> PARSOLONA = REGISTRY.register("parsolona", () -> new ParsolonaBlock());
	public static final RegistryObject<Block> SABRINA = REGISTRY.register("sabrina", () -> new SabrinaBlock());
	public static final RegistryObject<Block> PRES_BULON = REGISTRY.register("pres_bulon", () -> new PresBulonBlock());
	public static final RegistryObject<Block> HUMBOURGEUR = REGISTRY.register("humbourgeur", () -> new HumbourgeurBlock());
	public static final RegistryObject<Block> NORD = REGISTRY.register("nord", () -> new NordBlock());
	public static final RegistryObject<Block> FIOUSE = REGISTRY.register("fiouse", () -> new FiouseBlock());
	public static final RegistryObject<Block> ORIENTAL = REGISTRY.register("oriental", () -> new OrientalBlock());
	public static final RegistryObject<Block> MONT = REGISTRY.register("mont", () -> new MontBlock());
	public static final RegistryObject<Block> CHAMPSDEDAVI = REGISTRY.register("champsdedavi", () -> new ChampsdedaviBlock());
	public static final RegistryObject<Block> ARMAGEDDON = REGISTRY.register("armageddon", () -> new ArmageddonBlock());
	public static final RegistryObject<Block> TETEDU = REGISTRY.register("tetedu", () -> new TeteduBlock());
	public static final RegistryObject<Block> MATERNEL = REGISTRY.register("maternel", () -> new MaternelBlock());
	public static final RegistryObject<Block> DEMI_CIEL = REGISTRY.register("demi_ciel", () -> new DemiCielBlock());
	public static final RegistryObject<Block> PORTEAUBOIS = REGISTRY.register("porteaubois", () -> new PorteauboisBlock());
	public static final RegistryObject<Block> CHAMPONAIS = REGISTRY.register("champonais", () -> new ChamponaisBlock());
	public static final RegistryObject<Block> MASTEUR = REGISTRY.register("masteur", () -> new MasteurBlock());
	public static final RegistryObject<Block> FLOCH = REGISTRY.register("floch", () -> new FlochBlock());
	public static final RegistryObject<Block> LUMIERE = REGISTRY.register("lumiere", () -> new LumiereBlock());
	public static final RegistryObject<Block> CHEMINEE = REGISTRY.register("cheminee", () -> new ChemineeBlock());
	public static final RegistryObject<Block> STARLESS = REGISTRY.register("starless", () -> new StarlessBlock());
	public static final RegistryObject<Block> TRIDENT = REGISTRY.register("trident", () -> new TridentBlock());
	public static final RegistryObject<Block> BANLETA = REGISTRY.register("banleta", () -> new BanletaBlock());
	public static final RegistryObject<Block> AN = REGISTRY.register("an", () -> new AnBlock());
	public static final RegistryObject<Block> SAMRUTO = REGISTRY.register("samruto", () -> new SamrutoBlock());
	public static final RegistryObject<Block> DACHAN = REGISTRY.register("dachan", () -> new DachanBlock());
	public static final RegistryObject<Block> CRYTALINE = REGISTRY.register("crytaline", () -> new CrytalineBlock());
	public static final RegistryObject<Block> KYOU = REGISTRY.register("kyou", () -> new KyouBlock());
	public static final RegistryObject<Block> ECOLES_NT = REGISTRY.register("ecoles_nt", () -> new EcolesNTBlock());
	public static final RegistryObject<Block> RESIDANCE_NT = REGISTRY.register("residance_nt", () -> new ResidanceNTBlock());
	public static final RegistryObject<Block> PONTDELAUBE_NT = REGISTRY.register("pontdelaube_nt", () -> new PontdelaubeNTBlock());
	public static final RegistryObject<Block> MAGASINS_USINE_NT = REGISTRY.register("magasins_usine_nt", () -> new MagasinsUsineNTBlock());
}
