
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.blocblocthebloc.bussounds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import fr.blocblocthebloc.bussounds.BussoundsMod;

public class BussoundsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, BussoundsMod.MODID);
	public static final RegistryObject<Item> PLACE_CAMPAGNE = block(BussoundsModBlocks.PLACE_CAMPAGNE);
	public static final RegistryObject<Item> CHAMPS_DE_BLE = block(BussoundsModBlocks.CHAMPS_DE_BLE);
	public static final RegistryObject<Item> SOGZIT = block(BussoundsModBlocks.SOGZIT);
	public static final RegistryObject<Item> PAIN = block(BussoundsModBlocks.PAIN);
	public static final RegistryObject<Item> FEB_21 = block(BussoundsModBlocks.FEB_21);
	public static final RegistryObject<Item> PARC_COMMUN = block(BussoundsModBlocks.PARC_COMMUN);
	public static final RegistryObject<Item> ROUST = block(BussoundsModBlocks.ROUST);
	public static final RegistryObject<Item> POINT_BRONZE = block(BussoundsModBlocks.POINT_BRONZE);
	public static final RegistryObject<Item> CENTRE_VILLE = block(BussoundsModBlocks.CENTRE_VILLE);
	public static final RegistryObject<Item> GARE = block(BussoundsModBlocks.GARE);
	public static final RegistryObject<Item> CASTADREAM = block(BussoundsModBlocks.CASTADREAM);
	public static final RegistryObject<Item> FEB_29 = block(BussoundsModBlocks.FEB_29);
	public static final RegistryObject<Item> LITIEUM = block(BussoundsModBlocks.LITIEUM);
	public static final RegistryObject<Item> FRANK = block(BussoundsModBlocks.FRANK);
	public static final RegistryObject<Item> ABBY = block(BussoundsModBlocks.ABBY);
	public static final RegistryObject<Item> DECOLOR = block(BussoundsModBlocks.DECOLOR);
	public static final RegistryObject<Item> ROLAND = block(BussoundsModBlocks.ROLAND);
	public static final RegistryObject<Item> CENTRE_LOGISTIQUE = block(BussoundsModBlocks.CENTRE_LOGISTIQUE);
	public static final RegistryObject<Item> ILE = block(BussoundsModBlocks.ILE);
	public static final RegistryObject<Item> FEUWAR = block(BussoundsModBlocks.FEUWAR);
	public static final RegistryObject<Item> RAILS = block(BussoundsModBlocks.RAILS);
	public static final RegistryObject<Item> CIMETIERE = block(BussoundsModBlocks.CIMETIERE);
	public static final RegistryObject<Item> RUE = block(BussoundsModBlocks.RUE);
	public static final RegistryObject<Item> NOV_11 = block(BussoundsModBlocks.NOV_11);
	public static final RegistryObject<Item> CAMPAGNE = block(BussoundsModBlocks.CAMPAGNE);
	public static final RegistryObject<Item> FONTAINE = block(BussoundsModBlocks.FONTAINE);
	public static final RegistryObject<Item> CHARMAUX = block(BussoundsModBlocks.CHARMAUX);
	public static final RegistryObject<Item> PONTDEAU = block(BussoundsModBlocks.PONTDEAU);
	public static final RegistryObject<Item> FLAURETE = block(BussoundsModBlocks.FLAURETE);
	public static final RegistryObject<Item> DURIAN = block(BussoundsModBlocks.DURIAN);
	public static final RegistryObject<Item> TROUBADOUR = block(BussoundsModBlocks.TROUBADOUR);
	public static final RegistryObject<Item> ST_POULIN = block(BussoundsModBlocks.ST_POULIN);
	public static final RegistryObject<Item> EDUICO = block(BussoundsModBlocks.EDUICO);
	public static final RegistryObject<Item> MAIS_1 = block(BussoundsModBlocks.MAIS_1);
	public static final RegistryObject<Item> THEATRE = block(BussoundsModBlocks.THEATRE);
	public static final RegistryObject<Item> VITICUL = block(BussoundsModBlocks.VITICUL);
	public static final RegistryObject<Item> OUTILS = block(BussoundsModBlocks.OUTILS);
	public static final RegistryObject<Item> NUANCES = block(BussoundsModBlocks.NUANCES);
	public static final RegistryObject<Item> POINT_ROND = block(BussoundsModBlocks.POINT_ROND);
	public static final RegistryObject<Item> SANS = block(BussoundsModBlocks.SANS);
	public static final RegistryObject<Item> CORPS = block(BussoundsModBlocks.CORPS);
	public static final RegistryObject<Item> JUI_14 = block(BussoundsModBlocks.JUI_14);
	public static final RegistryObject<Item> LEGUERRIER = block(BussoundsModBlocks.LEGUERRIER);
	public static final RegistryObject<Item> RESIDANCE = block(BussoundsModBlocks.RESIDANCE);
	public static final RegistryObject<Item> RENAR = block(BussoundsModBlocks.RENAR);
	public static final RegistryObject<Item> SOURCES = block(BussoundsModBlocks.SOURCES);
	public static final RegistryObject<Item> ROMAINS = block(BussoundsModBlocks.ROMAINS);
	public static final RegistryObject<Item> FEU_B = block(BussoundsModBlocks.FEU_B);
	public static final RegistryObject<Item> JAN_1 = block(BussoundsModBlocks.JAN_1);
	public static final RegistryObject<Item> RESTAURATION = block(BussoundsModBlocks.RESTAURATION);
	public static final RegistryObject<Item> MARCHE = block(BussoundsModBlocks.MARCHE);
	public static final RegistryObject<Item> THEO = block(BussoundsModBlocks.THEO);
	public static final RegistryObject<Item> ROUDIN = block(BussoundsModBlocks.ROUDIN);
	public static final RegistryObject<Item> CENTRE_ADMINISTRATIF = block(BussoundsModBlocks.CENTRE_ADMINISTRATIF);
	public static final RegistryObject<Item> CHEMIN = block(BussoundsModBlocks.CHEMIN);
	public static final RegistryObject<Item> DELACOUR = block(BussoundsModBlocks.DELACOUR);
	public static final RegistryObject<Item> MANIA = block(BussoundsModBlocks.MANIA);
	public static final RegistryObject<Item> MAIS = block(BussoundsModBlocks.MAIS);
	public static final RegistryObject<Item> DUCARTON = block(BussoundsModBlocks.DUCARTON);
	public static final RegistryObject<Item> TUNES = block(BussoundsModBlocks.TUNES);
	public static final RegistryObject<Item> HOPITAL = block(BussoundsModBlocks.HOPITAL);
	public static final RegistryObject<Item> LAMCOMBRE = block(BussoundsModBlocks.LAMCOMBRE);
	public static final RegistryObject<Item> LACANAILE = block(BussoundsModBlocks.LACANAILE);
	public static final RegistryObject<Item> ANCIENNE_GARE = block(BussoundsModBlocks.ANCIENNE_GARE);
	public static final RegistryObject<Item> CLINIQUE = block(BussoundsModBlocks.CLINIQUE);
	public static final RegistryObject<Item> APPARTEMENT = block(BussoundsModBlocks.APPARTEMENT);
	public static final RegistryObject<Item> AURELIEN = block(BussoundsModBlocks.AURELIEN);
	public static final RegistryObject<Item> USE = block(BussoundsModBlocks.USE);
	public static final RegistryObject<Item> SURCOTE = block(BussoundsModBlocks.SURCOTE);
	public static final RegistryObject<Item> PIGMENT = block(BussoundsModBlocks.PIGMENT);
	public static final RegistryObject<Item> POTAGE = block(BussoundsModBlocks.POTAGE);
	public static final RegistryObject<Item> DUBOULANGE = block(BussoundsModBlocks.DUBOULANGE);
	public static final RegistryObject<Item> ETE = block(BussoundsModBlocks.ETE);
	public static final RegistryObject<Item> MAGASINS_USINE = block(BussoundsModBlocks.MAGASINS_USINE);
	public static final RegistryObject<Item> CENTRE_COMMERCIAL = block(BussoundsModBlocks.CENTRE_COMMERCIAL);
	public static final RegistryObject<Item> THELAY = block(BussoundsModBlocks.THELAY);
	public static final RegistryObject<Item> OLMAR = block(BussoundsModBlocks.OLMAR);
	public static final RegistryObject<Item> BOURSE = block(BussoundsModBlocks.BOURSE);
	public static final RegistryObject<Item> LOUIS = block(BussoundsModBlocks.LOUIS);
	public static final RegistryObject<Item> PARVI = block(BussoundsModBlocks.PARVI);
	public static final RegistryObject<Item> DEGANT = block(BussoundsModBlocks.DEGANT);
	public static final RegistryObject<Item> PASSAGE = block(BussoundsModBlocks.PASSAGE);
	public static final RegistryObject<Item> NAGI = block(BussoundsModBlocks.NAGI);
	public static final RegistryObject<Item> COEUR = block(BussoundsModBlocks.COEUR);
	public static final RegistryObject<Item> PAIX = block(BussoundsModBlocks.PAIX);
	public static final RegistryObject<Item> CHARB = block(BussoundsModBlocks.CHARB);
	public static final RegistryObject<Item> LOGE = block(BussoundsModBlocks.LOGE);
	public static final RegistryObject<Item> COLLEGE_ST_DEMAIN = block(BussoundsModBlocks.COLLEGE_ST_DEMAIN);
	public static final RegistryObject<Item> KIRO = block(BussoundsModBlocks.KIRO);
	public static final RegistryObject<Item> UNIVERSITE = block(BussoundsModBlocks.UNIVERSITE);
	public static final RegistryObject<Item> CAMPUS = block(BussoundsModBlocks.CAMPUS);
	public static final RegistryObject<Item> ECOLES = block(BussoundsModBlocks.ECOLES);
	public static final RegistryObject<Item> CHANTS = block(BussoundsModBlocks.CHANTS);
	public static final RegistryObject<Item> VERTI = block(BussoundsModBlocks.VERTI);
	public static final RegistryObject<Item> MARTRE = block(BussoundsModBlocks.MARTRE);
	public static final RegistryObject<Item> LITHYA = block(BussoundsModBlocks.LITHYA);
	public static final RegistryObject<Item> SOLEIL = block(BussoundsModBlocks.SOLEIL);
	public static final RegistryObject<Item> SOUSCOTE = block(BussoundsModBlocks.SOUSCOTE);
	public static final RegistryObject<Item> ELEMENTO = block(BussoundsModBlocks.ELEMENTO);
	public static final RegistryObject<Item> PONTDELAUBE = block(BussoundsModBlocks.PONTDELAUBE);
	public static final RegistryObject<Item> BULON = block(BussoundsModBlocks.BULON);
	public static final RegistryObject<Item> HABITACLE = block(BussoundsModBlocks.HABITACLE);
	public static final RegistryObject<Item> LUEN = block(BussoundsModBlocks.LUEN);
	public static final RegistryObject<Item> HAKIM = block(BussoundsModBlocks.HAKIM);
	public static final RegistryObject<Item> SOUFFLERIE = block(BussoundsModBlocks.SOUFFLERIE);
	public static final RegistryObject<Item> CALAMARDE = block(BussoundsModBlocks.CALAMARDE);
	public static final RegistryObject<Item> PARC_LOGISTIQUE = block(BussoundsModBlocks.PARC_LOGISTIQUE);
	public static final RegistryObject<Item> TAILS = block(BussoundsModBlocks.TAILS);
	public static final RegistryObject<Item> PONTDELAIR = block(BussoundsModBlocks.PONTDELAIR);
	public static final RegistryObject<Item> JARDINSDELA_GARE = block(BussoundsModBlocks.JARDINSDELA_GARE);
	public static final RegistryObject<Item> GARE_CENTRALE = block(BussoundsModBlocks.GARE_CENTRALE);
	public static final RegistryObject<Item> MAIRIE = block(BussoundsModBlocks.MAIRIE);
	public static final RegistryObject<Item> ROULONI = block(BussoundsModBlocks.ROULONI);
	public static final RegistryObject<Item> SEP_1 = block(BussoundsModBlocks.SEP_1);
	public static final RegistryObject<Item> PARSOLONA = block(BussoundsModBlocks.PARSOLONA);
	public static final RegistryObject<Item> SABRINA = block(BussoundsModBlocks.SABRINA);
	public static final RegistryObject<Item> PRES_BULON = block(BussoundsModBlocks.PRES_BULON);
	public static final RegistryObject<Item> HUMBOURGEUR = block(BussoundsModBlocks.HUMBOURGEUR);
	public static final RegistryObject<Item> NORD = block(BussoundsModBlocks.NORD);
	public static final RegistryObject<Item> FIOUSE = block(BussoundsModBlocks.FIOUSE);
	public static final RegistryObject<Item> ORIENTAL = block(BussoundsModBlocks.ORIENTAL);
	public static final RegistryObject<Item> MONT = block(BussoundsModBlocks.MONT);
	public static final RegistryObject<Item> CHAMPSDEDAVI = block(BussoundsModBlocks.CHAMPSDEDAVI);
	public static final RegistryObject<Item> ARMAGEDDON = block(BussoundsModBlocks.ARMAGEDDON);
	public static final RegistryObject<Item> TETEDU = block(BussoundsModBlocks.TETEDU);
	public static final RegistryObject<Item> MATERNEL = block(BussoundsModBlocks.MATERNEL);
	public static final RegistryObject<Item> DEMI_CIEL = block(BussoundsModBlocks.DEMI_CIEL);
	public static final RegistryObject<Item> PORTEAUBOIS = block(BussoundsModBlocks.PORTEAUBOIS);
	public static final RegistryObject<Item> CHAMPONAIS = block(BussoundsModBlocks.CHAMPONAIS);
	public static final RegistryObject<Item> MASTEUR = block(BussoundsModBlocks.MASTEUR);
	public static final RegistryObject<Item> FLOCH = block(BussoundsModBlocks.FLOCH);
	public static final RegistryObject<Item> LUMIERE = block(BussoundsModBlocks.LUMIERE);
	public static final RegistryObject<Item> CHEMINEE = block(BussoundsModBlocks.CHEMINEE);
	public static final RegistryObject<Item> STARLESS = block(BussoundsModBlocks.STARLESS);
	public static final RegistryObject<Item> TRIDENT = block(BussoundsModBlocks.TRIDENT);
	public static final RegistryObject<Item> BANLETA = block(BussoundsModBlocks.BANLETA);
	public static final RegistryObject<Item> AN = block(BussoundsModBlocks.AN);
	public static final RegistryObject<Item> SAMRUTO = block(BussoundsModBlocks.SAMRUTO);
	public static final RegistryObject<Item> DACHAN = block(BussoundsModBlocks.DACHAN);
	public static final RegistryObject<Item> CRYTALINE = block(BussoundsModBlocks.CRYTALINE);
	public static final RegistryObject<Item> KYOU = block(BussoundsModBlocks.KYOU);
	public static final RegistryObject<Item> ECOLES_NT = block(BussoundsModBlocks.ECOLES_NT);
	public static final RegistryObject<Item> RESIDANCE_NT = block(BussoundsModBlocks.RESIDANCE_NT);
	public static final RegistryObject<Item> PONTDELAUBE_NT = block(BussoundsModBlocks.PONTDELAUBE_NT);
	public static final RegistryObject<Item> MAGASINS_USINE_NT = block(BussoundsModBlocks.MAGASINS_USINE_NT);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
