
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.blocblocthebloc.bussounds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.sounds.SoundEvent;
import net.minecraft.resources.ResourceLocation;

import fr.blocblocthebloc.bussounds.BussoundsMod;

public class BussoundsModSounds {
	public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, BussoundsMod.MODID);
	public static final RegistryObject<SoundEvent> PLACE_CAMPAGNE = REGISTRY.register("place_campagne", () -> new SoundEvent(new ResourceLocation("bussounds", "place_campagne")));
	public static final RegistryObject<SoundEvent> CHAMPS_DE_BLE = REGISTRY.register("champs_de_ble", () -> new SoundEvent(new ResourceLocation("bussounds", "champs_de_ble")));
	public static final RegistryObject<SoundEvent> SOGZIT = REGISTRY.register("sogzit", () -> new SoundEvent(new ResourceLocation("bussounds", "sogzit")));
	public static final RegistryObject<SoundEvent> PAIN = REGISTRY.register("pain", () -> new SoundEvent(new ResourceLocation("bussounds", "pain")));
	public static final RegistryObject<SoundEvent> FEB_21 = REGISTRY.register("feb_21", () -> new SoundEvent(new ResourceLocation("bussounds", "feb_21")));
	public static final RegistryObject<SoundEvent> PARC_COMMUN = REGISTRY.register("parc_commun", () -> new SoundEvent(new ResourceLocation("bussounds", "parc_commun")));
	public static final RegistryObject<SoundEvent> ROUST = REGISTRY.register("roust", () -> new SoundEvent(new ResourceLocation("bussounds", "roust")));
	public static final RegistryObject<SoundEvent> POINT_BRONZE = REGISTRY.register("point_bronze", () -> new SoundEvent(new ResourceLocation("bussounds", "point_bronze")));
	public static final RegistryObject<SoundEvent> CENTRE_VILLE = REGISTRY.register("centre_ville", () -> new SoundEvent(new ResourceLocation("bussounds", "centre_ville")));
	public static final RegistryObject<SoundEvent> GARE = REGISTRY.register("gare", () -> new SoundEvent(new ResourceLocation("bussounds", "gare")));
	public static final RegistryObject<SoundEvent> CASTADREAM = REGISTRY.register("castadream", () -> new SoundEvent(new ResourceLocation("bussounds", "castadream")));
	public static final RegistryObject<SoundEvent> FEB_29 = REGISTRY.register("feb_29", () -> new SoundEvent(new ResourceLocation("bussounds", "feb_29")));
	public static final RegistryObject<SoundEvent> LITIEUM = REGISTRY.register("litieum", () -> new SoundEvent(new ResourceLocation("bussounds", "litieum")));
	public static final RegistryObject<SoundEvent> FRANK = REGISTRY.register("frank", () -> new SoundEvent(new ResourceLocation("bussounds", "frank")));
	public static final RegistryObject<SoundEvent> ABBY = REGISTRY.register("abby", () -> new SoundEvent(new ResourceLocation("bussounds", "abby")));
	public static final RegistryObject<SoundEvent> DECOLOR = REGISTRY.register("decolor", () -> new SoundEvent(new ResourceLocation("bussounds", "decolor")));
	public static final RegistryObject<SoundEvent> ROLAND = REGISTRY.register("roland", () -> new SoundEvent(new ResourceLocation("bussounds", "roland")));
	public static final RegistryObject<SoundEvent> CENTRE_LOGISTIQUE = REGISTRY.register("centre_logistique", () -> new SoundEvent(new ResourceLocation("bussounds", "centre_logistique")));
	public static final RegistryObject<SoundEvent> ILE = REGISTRY.register("ile", () -> new SoundEvent(new ResourceLocation("bussounds", "ile")));
	public static final RegistryObject<SoundEvent> FEUWAR = REGISTRY.register("feuwar", () -> new SoundEvent(new ResourceLocation("bussounds", "feuwar")));
	public static final RegistryObject<SoundEvent> RAILS = REGISTRY.register("rails", () -> new SoundEvent(new ResourceLocation("bussounds", "rails")));
	public static final RegistryObject<SoundEvent> CIMETIERE = REGISTRY.register("cimetiere", () -> new SoundEvent(new ResourceLocation("bussounds", "cimetiere")));
	public static final RegistryObject<SoundEvent> RUE = REGISTRY.register("rue", () -> new SoundEvent(new ResourceLocation("bussounds", "rue")));
	public static final RegistryObject<SoundEvent> NOV_11 = REGISTRY.register("nov_11", () -> new SoundEvent(new ResourceLocation("bussounds", "nov_11")));
	public static final RegistryObject<SoundEvent> CAMPAGNE = REGISTRY.register("campagne", () -> new SoundEvent(new ResourceLocation("bussounds", "campagne")));
	public static final RegistryObject<SoundEvent> FONTAINE = REGISTRY.register("fontaine", () -> new SoundEvent(new ResourceLocation("bussounds", "fontaine")));
	public static final RegistryObject<SoundEvent> CHARMAUX = REGISTRY.register("charmaux", () -> new SoundEvent(new ResourceLocation("bussounds", "charmaux")));
	public static final RegistryObject<SoundEvent> PONT_DEAU = REGISTRY.register("pont_deau", () -> new SoundEvent(new ResourceLocation("bussounds", "pont_deau")));
	public static final RegistryObject<SoundEvent> FLAURETE = REGISTRY.register("flaurete", () -> new SoundEvent(new ResourceLocation("bussounds", "flaurete")));
	public static final RegistryObject<SoundEvent> DURIAN = REGISTRY.register("durian", () -> new SoundEvent(new ResourceLocation("bussounds", "durian")));
	public static final RegistryObject<SoundEvent> TROUBADOUR = REGISTRY.register("troubadour", () -> new SoundEvent(new ResourceLocation("bussounds", "troubadour")));
	public static final RegistryObject<SoundEvent> ST_POULIN = REGISTRY.register("st_poulin", () -> new SoundEvent(new ResourceLocation("bussounds", "st_poulin")));
	public static final RegistryObject<SoundEvent> EDUICO = REGISTRY.register("eduico", () -> new SoundEvent(new ResourceLocation("bussounds", "eduico")));
	public static final RegistryObject<SoundEvent> MAIS_1 = REGISTRY.register("mais_1", () -> new SoundEvent(new ResourceLocation("bussounds", "mais_1")));
	public static final RegistryObject<SoundEvent> THEATRE = REGISTRY.register("theatre", () -> new SoundEvent(new ResourceLocation("bussounds", "theatre")));
	public static final RegistryObject<SoundEvent> VITICUL = REGISTRY.register("viticul", () -> new SoundEvent(new ResourceLocation("bussounds", "viticul")));
	public static final RegistryObject<SoundEvent> OUTILS = REGISTRY.register("outils", () -> new SoundEvent(new ResourceLocation("bussounds", "outils")));
	public static final RegistryObject<SoundEvent> NUANCES = REGISTRY.register("nuances", () -> new SoundEvent(new ResourceLocation("bussounds", "nuances")));
	public static final RegistryObject<SoundEvent> POINT_ROND = REGISTRY.register("point_rond", () -> new SoundEvent(new ResourceLocation("bussounds", "point_rond")));
	public static final RegistryObject<SoundEvent> SANS = REGISTRY.register("sans", () -> new SoundEvent(new ResourceLocation("bussounds", "sans")));
	public static final RegistryObject<SoundEvent> CORPS = REGISTRY.register("corps", () -> new SoundEvent(new ResourceLocation("bussounds", "corps")));
	public static final RegistryObject<SoundEvent> JUI_14 = REGISTRY.register("jui_14", () -> new SoundEvent(new ResourceLocation("bussounds", "jui_14")));
	public static final RegistryObject<SoundEvent> LEGUERRIER = REGISTRY.register("leguerrier", () -> new SoundEvent(new ResourceLocation("bussounds", "leguerrier")));
	public static final RegistryObject<SoundEvent> RESIDANCE = REGISTRY.register("residance", () -> new SoundEvent(new ResourceLocation("bussounds", "residance")));
	public static final RegistryObject<SoundEvent> RENAR = REGISTRY.register("renar", () -> new SoundEvent(new ResourceLocation("bussounds", "renar")));
	public static final RegistryObject<SoundEvent> SOURCES = REGISTRY.register("sources", () -> new SoundEvent(new ResourceLocation("bussounds", "sources")));
	public static final RegistryObject<SoundEvent> ROMAINS = REGISTRY.register("romains", () -> new SoundEvent(new ResourceLocation("bussounds", "romains")));
	public static final RegistryObject<SoundEvent> FEU = REGISTRY.register("feu", () -> new SoundEvent(new ResourceLocation("bussounds", "feu")));
	public static final RegistryObject<SoundEvent> JANV_1 = REGISTRY.register("janv_1", () -> new SoundEvent(new ResourceLocation("bussounds", "janv_1")));
	public static final RegistryObject<SoundEvent> RESTAURATION = REGISTRY.register("restauration", () -> new SoundEvent(new ResourceLocation("bussounds", "restauration")));
	public static final RegistryObject<SoundEvent> MARCHE = REGISTRY.register("marche", () -> new SoundEvent(new ResourceLocation("bussounds", "marche")));
	public static final RegistryObject<SoundEvent> THEO = REGISTRY.register("theo", () -> new SoundEvent(new ResourceLocation("bussounds", "theo")));
	public static final RegistryObject<SoundEvent> ROUDIN = REGISTRY.register("roudin", () -> new SoundEvent(new ResourceLocation("bussounds", "roudin")));
	public static final RegistryObject<SoundEvent> CENTRE_ADMINISTRATIF = REGISTRY.register("centre_administratif", () -> new SoundEvent(new ResourceLocation("bussounds", "centre_administratif")));
	public static final RegistryObject<SoundEvent> CHEMIN = REGISTRY.register("chemin", () -> new SoundEvent(new ResourceLocation("bussounds", "chemin")));
	public static final RegistryObject<SoundEvent> DELACOUR = REGISTRY.register("delacour", () -> new SoundEvent(new ResourceLocation("bussounds", "delacour")));
	public static final RegistryObject<SoundEvent> MANIA = REGISTRY.register("mania", () -> new SoundEvent(new ResourceLocation("bussounds", "mania")));
	public static final RegistryObject<SoundEvent> MAIS = REGISTRY.register("mais", () -> new SoundEvent(new ResourceLocation("bussounds", "mais")));
	public static final RegistryObject<SoundEvent> DUCARTON = REGISTRY.register("ducarton", () -> new SoundEvent(new ResourceLocation("bussounds", "ducarton")));
	public static final RegistryObject<SoundEvent> TUNES = REGISTRY.register("tunes", () -> new SoundEvent(new ResourceLocation("bussounds", "tunes")));
	public static final RegistryObject<SoundEvent> HOPITAL = REGISTRY.register("hopital", () -> new SoundEvent(new ResourceLocation("bussounds", "hopital")));
	public static final RegistryObject<SoundEvent> LAMCOMBRE = REGISTRY.register("lamcombre", () -> new SoundEvent(new ResourceLocation("bussounds", "lamcombre")));
	public static final RegistryObject<SoundEvent> LACANAILE = REGISTRY.register("lacanaile", () -> new SoundEvent(new ResourceLocation("bussounds", "lacanaile")));
	public static final RegistryObject<SoundEvent> ANCIENNE_GARE = REGISTRY.register("ancienne_gare", () -> new SoundEvent(new ResourceLocation("bussounds", "ancienne_gare")));
	public static final RegistryObject<SoundEvent> CLINIQUE = REGISTRY.register("clinique", () -> new SoundEvent(new ResourceLocation("bussounds", "clinique")));
	public static final RegistryObject<SoundEvent> APPARTEMENT = REGISTRY.register("appartement", () -> new SoundEvent(new ResourceLocation("bussounds", "appartement")));
	public static final RegistryObject<SoundEvent> AURELIEN = REGISTRY.register("aurelien", () -> new SoundEvent(new ResourceLocation("bussounds", "aurelien")));
	public static final RegistryObject<SoundEvent> USE = REGISTRY.register("use", () -> new SoundEvent(new ResourceLocation("bussounds", "use")));
	public static final RegistryObject<SoundEvent> SURCOTE = REGISTRY.register("surcote", () -> new SoundEvent(new ResourceLocation("bussounds", "surcote")));
	public static final RegistryObject<SoundEvent> PIGMENT = REGISTRY.register("pigment", () -> new SoundEvent(new ResourceLocation("bussounds", "pigment")));
	public static final RegistryObject<SoundEvent> POTAGE = REGISTRY.register("potage", () -> new SoundEvent(new ResourceLocation("bussounds", "potage")));
	public static final RegistryObject<SoundEvent> DUBOULANGE = REGISTRY.register("duboulange", () -> new SoundEvent(new ResourceLocation("bussounds", "duboulange")));
	public static final RegistryObject<SoundEvent> ETE = REGISTRY.register("ete", () -> new SoundEvent(new ResourceLocation("bussounds", "ete")));
	public static final RegistryObject<SoundEvent> MAGASINS_USINE = REGISTRY.register("magasins_usine", () -> new SoundEvent(new ResourceLocation("bussounds", "magasins_usine")));
	public static final RegistryObject<SoundEvent> CENTRE_COMMERCIAL = REGISTRY.register("centre_commercial", () -> new SoundEvent(new ResourceLocation("bussounds", "centre_commercial")));
	public static final RegistryObject<SoundEvent> THELAY = REGISTRY.register("thelay", () -> new SoundEvent(new ResourceLocation("bussounds", "thelay")));
	public static final RegistryObject<SoundEvent> OLMAR = REGISTRY.register("olmar", () -> new SoundEvent(new ResourceLocation("bussounds", "olmar")));
	public static final RegistryObject<SoundEvent> BOURSE = REGISTRY.register("bourse", () -> new SoundEvent(new ResourceLocation("bussounds", "bourse")));
	public static final RegistryObject<SoundEvent> LOUIS = REGISTRY.register("louis", () -> new SoundEvent(new ResourceLocation("bussounds", "louis")));
	public static final RegistryObject<SoundEvent> PARVI = REGISTRY.register("parvi", () -> new SoundEvent(new ResourceLocation("bussounds", "parvi")));
	public static final RegistryObject<SoundEvent> DEGANT = REGISTRY.register("degant", () -> new SoundEvent(new ResourceLocation("bussounds", "degant")));
	public static final RegistryObject<SoundEvent> PASSAGE = REGISTRY.register("passage", () -> new SoundEvent(new ResourceLocation("bussounds", "passage")));
	public static final RegistryObject<SoundEvent> NAGI = REGISTRY.register("nagi", () -> new SoundEvent(new ResourceLocation("bussounds", "nagi")));
	public static final RegistryObject<SoundEvent> COEUR = REGISTRY.register("coeur", () -> new SoundEvent(new ResourceLocation("bussounds", "coeur")));
	public static final RegistryObject<SoundEvent> PAIX = REGISTRY.register("paix", () -> new SoundEvent(new ResourceLocation("bussounds", "paix")));
	public static final RegistryObject<SoundEvent> CHAR = REGISTRY.register("char", () -> new SoundEvent(new ResourceLocation("bussounds", "char")));
	public static final RegistryObject<SoundEvent> LOGE = REGISTRY.register("loge", () -> new SoundEvent(new ResourceLocation("bussounds", "loge")));
	public static final RegistryObject<SoundEvent> COLLEGE_ST_DEMAIN = REGISTRY.register("college_st_demain", () -> new SoundEvent(new ResourceLocation("bussounds", "college_st_demain")));
	public static final RegistryObject<SoundEvent> KIRO = REGISTRY.register("kiro", () -> new SoundEvent(new ResourceLocation("bussounds", "kiro")));
	public static final RegistryObject<SoundEvent> UNIVERSITE = REGISTRY.register("universite", () -> new SoundEvent(new ResourceLocation("bussounds", "universite")));
	public static final RegistryObject<SoundEvent> CAMPUS = REGISTRY.register("campus", () -> new SoundEvent(new ResourceLocation("bussounds", "campus")));
	public static final RegistryObject<SoundEvent> ECOLES = REGISTRY.register("ecoles", () -> new SoundEvent(new ResourceLocation("bussounds", "ecoles")));
	public static final RegistryObject<SoundEvent> CHANTS = REGISTRY.register("chants", () -> new SoundEvent(new ResourceLocation("bussounds", "chants")));
	public static final RegistryObject<SoundEvent> VERTI = REGISTRY.register("verti", () -> new SoundEvent(new ResourceLocation("bussounds", "verti")));
	public static final RegistryObject<SoundEvent> MARTRE = REGISTRY.register("martre", () -> new SoundEvent(new ResourceLocation("bussounds", "martre")));
	public static final RegistryObject<SoundEvent> LITHYA = REGISTRY.register("lithya", () -> new SoundEvent(new ResourceLocation("bussounds", "lithya")));
	public static final RegistryObject<SoundEvent> SOLEIL = REGISTRY.register("soleil", () -> new SoundEvent(new ResourceLocation("bussounds", "soleil")));
	public static final RegistryObject<SoundEvent> SOUS_COTE = REGISTRY.register("sous_cote", () -> new SoundEvent(new ResourceLocation("bussounds", "sous_cote")));
	public static final RegistryObject<SoundEvent> ELEMENTO = REGISTRY.register("elemento", () -> new SoundEvent(new ResourceLocation("bussounds", "elemento")));
	public static final RegistryObject<SoundEvent> PONT_DE_LAUBE = REGISTRY.register("pont_de_laube", () -> new SoundEvent(new ResourceLocation("bussounds", "pont_de_laube")));
	public static final RegistryObject<SoundEvent> BULON = REGISTRY.register("bulon", () -> new SoundEvent(new ResourceLocation("bussounds", "bulon")));
	public static final RegistryObject<SoundEvent> HABITACLE = REGISTRY.register("habitacle", () -> new SoundEvent(new ResourceLocation("bussounds", "habitacle")));
	public static final RegistryObject<SoundEvent> LUEN = REGISTRY.register("luen", () -> new SoundEvent(new ResourceLocation("bussounds", "luen")));
	public static final RegistryObject<SoundEvent> HAKIM = REGISTRY.register("hakim", () -> new SoundEvent(new ResourceLocation("bussounds", "hakim")));
	public static final RegistryObject<SoundEvent> SOUFFLERIE = REGISTRY.register("soufflerie", () -> new SoundEvent(new ResourceLocation("bussounds", "soufflerie")));
	public static final RegistryObject<SoundEvent> CALAMARDE = REGISTRY.register("calamarde", () -> new SoundEvent(new ResourceLocation("bussounds", "calamarde")));
	public static final RegistryObject<SoundEvent> PARC_LOGISTIQUE = REGISTRY.register("parc_logistique", () -> new SoundEvent(new ResourceLocation("bussounds", "parc_logistique")));
	public static final RegistryObject<SoundEvent> TAILS = REGISTRY.register("tails", () -> new SoundEvent(new ResourceLocation("bussounds", "tails")));
	public static final RegistryObject<SoundEvent> PONT_DE_LAIR = REGISTRY.register("pont_de_lair", () -> new SoundEvent(new ResourceLocation("bussounds", "pont_de_lair")));
	public static final RegistryObject<SoundEvent> JARDINS_DE_LA_GARE = REGISTRY.register("jardins_de_la_gare", () -> new SoundEvent(new ResourceLocation("bussounds", "jardins_de_la_gare")));
	public static final RegistryObject<SoundEvent> GARE_CENTRALE = REGISTRY.register("gare_centrale", () -> new SoundEvent(new ResourceLocation("bussounds", "gare_centrale")));
	public static final RegistryObject<SoundEvent> MAIRIE = REGISTRY.register("mairie", () -> new SoundEvent(new ResourceLocation("bussounds", "mairie")));
	public static final RegistryObject<SoundEvent> ROULONI = REGISTRY.register("rouloni", () -> new SoundEvent(new ResourceLocation("bussounds", "rouloni")));
	public static final RegistryObject<SoundEvent> SEP_1 = REGISTRY.register("sep_1", () -> new SoundEvent(new ResourceLocation("bussounds", "sep_1")));
	public static final RegistryObject<SoundEvent> PARSOLONA = REGISTRY.register("parsolona", () -> new SoundEvent(new ResourceLocation("bussounds", "parsolona")));
	public static final RegistryObject<SoundEvent> SABRINA = REGISTRY.register("sabrina", () -> new SoundEvent(new ResourceLocation("bussounds", "sabrina")));
	public static final RegistryObject<SoundEvent> PRES_BULON = REGISTRY.register("pres_bulon", () -> new SoundEvent(new ResourceLocation("bussounds", "pres_bulon")));
	public static final RegistryObject<SoundEvent> HUMBOURGEUR = REGISTRY.register("humbourgeur", () -> new SoundEvent(new ResourceLocation("bussounds", "humbourgeur")));
	public static final RegistryObject<SoundEvent> NORD = REGISTRY.register("nord", () -> new SoundEvent(new ResourceLocation("bussounds", "nord")));
	public static final RegistryObject<SoundEvent> FIOUSE = REGISTRY.register("fiouse", () -> new SoundEvent(new ResourceLocation("bussounds", "fiouse")));
	public static final RegistryObject<SoundEvent> ORIENTAL = REGISTRY.register("oriental", () -> new SoundEvent(new ResourceLocation("bussounds", "oriental")));
	public static final RegistryObject<SoundEvent> MONT = REGISTRY.register("mont", () -> new SoundEvent(new ResourceLocation("bussounds", "mont")));
	public static final RegistryObject<SoundEvent> CHAMPS_DE_DAVI = REGISTRY.register("champs_de_davi", () -> new SoundEvent(new ResourceLocation("bussounds", "champs_de_davi")));
	public static final RegistryObject<SoundEvent> ARMAGEDDON = REGISTRY.register("armageddon", () -> new SoundEvent(new ResourceLocation("bussounds", "armageddon")));
	public static final RegistryObject<SoundEvent> TETEDU = REGISTRY.register("tetedu", () -> new SoundEvent(new ResourceLocation("bussounds", "tetedu")));
	public static final RegistryObject<SoundEvent> MATERNEL = REGISTRY.register("maternel", () -> new SoundEvent(new ResourceLocation("bussounds", "maternel")));
	public static final RegistryObject<SoundEvent> DEMI_CIEL = REGISTRY.register("demi-ciel", () -> new SoundEvent(new ResourceLocation("bussounds", "demi-ciel")));
	public static final RegistryObject<SoundEvent> PORTE_AU_BOIS = REGISTRY.register("porte_au_bois", () -> new SoundEvent(new ResourceLocation("bussounds", "porte_au_bois")));
	public static final RegistryObject<SoundEvent> CHAMPONAIS = REGISTRY.register("champonais", () -> new SoundEvent(new ResourceLocation("bussounds", "champonais")));
	public static final RegistryObject<SoundEvent> MASTEUR = REGISTRY.register("masteur", () -> new SoundEvent(new ResourceLocation("bussounds", "masteur")));
	public static final RegistryObject<SoundEvent> FLOCH = REGISTRY.register("floch", () -> new SoundEvent(new ResourceLocation("bussounds", "floch")));
	public static final RegistryObject<SoundEvent> LUMIERE = REGISTRY.register("lumiere", () -> new SoundEvent(new ResourceLocation("bussounds", "lumiere")));
	public static final RegistryObject<SoundEvent> CHEMINEE = REGISTRY.register("cheminee", () -> new SoundEvent(new ResourceLocation("bussounds", "cheminee")));
	public static final RegistryObject<SoundEvent> STARLESS = REGISTRY.register("starless", () -> new SoundEvent(new ResourceLocation("bussounds", "starless")));
	public static final RegistryObject<SoundEvent> TRIDENT = REGISTRY.register("trident", () -> new SoundEvent(new ResourceLocation("bussounds", "trident")));
	public static final RegistryObject<SoundEvent> BANLETA = REGISTRY.register("banleta", () -> new SoundEvent(new ResourceLocation("bussounds", "banleta")));
	public static final RegistryObject<SoundEvent> AN = REGISTRY.register("an", () -> new SoundEvent(new ResourceLocation("bussounds", "an")));
	public static final RegistryObject<SoundEvent> SAMRUTO = REGISTRY.register("samruto", () -> new SoundEvent(new ResourceLocation("bussounds", "samruto")));
	public static final RegistryObject<SoundEvent> DACHAN = REGISTRY.register("dachan", () -> new SoundEvent(new ResourceLocation("bussounds", "dachan")));
	public static final RegistryObject<SoundEvent> CRYTALINE = REGISTRY.register("crytaline", () -> new SoundEvent(new ResourceLocation("bussounds", "crytaline")));
	public static final RegistryObject<SoundEvent> KYOU = REGISTRY.register("kyou", () -> new SoundEvent(new ResourceLocation("bussounds", "kyou")));
	public static final RegistryObject<SoundEvent> ECOLESNT = REGISTRY.register("ecolesnt", () -> new SoundEvent(new ResourceLocation("bussounds", "ecolesnt")));
	public static final RegistryObject<SoundEvent> RESIDANCENT = REGISTRY.register("residancent", () -> new SoundEvent(new ResourceLocation("bussounds", "residancent")));
	public static final RegistryObject<SoundEvent> PONT_DE_LAUBENT = REGISTRY.register("pont_de_laubent", () -> new SoundEvent(new ResourceLocation("bussounds", "pont_de_laubent")));
	public static final RegistryObject<SoundEvent> MAGASINS_USINENT = REGISTRY.register("magasins_usinent", () -> new SoundEvent(new ResourceLocation("bussounds", "magasins_usinent")));
}
