
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package fr.blocblocthebloc.bussounds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import fr.blocblocthebloc.bussounds.BussoundsMod;

public class BussoundsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, BussoundsMod.MODID);
	public static final RegistryObject<Item> PLACE_CAMPAGNE = block(BussoundsModBlocks.PLACE_CAMPAGNE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHAMPS_DE_BLE = block(BussoundsModBlocks.CHAMPS_DE_BLE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SOGZIT = block(BussoundsModBlocks.SOGZIT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PAIN = block(BussoundsModBlocks.PAIN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FEB_21 = block(BussoundsModBlocks.FEB_21, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PARC_COMMUN = block(BussoundsModBlocks.PARC_COMMUN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ROUST = block(BussoundsModBlocks.ROUST, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> POINT_BRONZE = block(BussoundsModBlocks.POINT_BRONZE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CENTRE_VILLE = block(BussoundsModBlocks.CENTRE_VILLE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> GARE = block(BussoundsModBlocks.GARE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CASTADREAM = block(BussoundsModBlocks.CASTADREAM, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FEB_29 = block(BussoundsModBlocks.FEB_29, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LITIEUM = block(BussoundsModBlocks.LITIEUM, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FRANK = block(BussoundsModBlocks.FRANK, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ABBY = block(BussoundsModBlocks.ABBY, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DECOLOR = block(BussoundsModBlocks.DECOLOR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ROLAND = block(BussoundsModBlocks.ROLAND, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CENTRE_LOGISTIQUE = block(BussoundsModBlocks.CENTRE_LOGISTIQUE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ILE = block(BussoundsModBlocks.ILE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FEUWAR = block(BussoundsModBlocks.FEUWAR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RAILS = block(BussoundsModBlocks.RAILS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CIMETIERE = block(BussoundsModBlocks.CIMETIERE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RUE = block(BussoundsModBlocks.RUE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> NOV_11 = block(BussoundsModBlocks.NOV_11, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CAMPAGNE = block(BussoundsModBlocks.CAMPAGNE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FONTAINE = block(BussoundsModBlocks.FONTAINE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHARMAUX = block(BussoundsModBlocks.CHARMAUX, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PONTDEAU = block(BussoundsModBlocks.PONTDEAU, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FLAURETE = block(BussoundsModBlocks.FLAURETE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DURIAN = block(BussoundsModBlocks.DURIAN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> TROUBADOUR = block(BussoundsModBlocks.TROUBADOUR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ST_POULIN = block(BussoundsModBlocks.ST_POULIN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> EDUICO = block(BussoundsModBlocks.EDUICO, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MAIS_1 = block(BussoundsModBlocks.MAIS_1, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> THEATRE = block(BussoundsModBlocks.THEATRE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> VITICUL = block(BussoundsModBlocks.VITICUL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> OUTILS = block(BussoundsModBlocks.OUTILS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> NUANCES = block(BussoundsModBlocks.NUANCES, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> POINT_ROND = block(BussoundsModBlocks.POINT_ROND, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SANS = block(BussoundsModBlocks.SANS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CORPS = block(BussoundsModBlocks.CORPS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> JUI_14 = block(BussoundsModBlocks.JUI_14, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LEGUERRIER = block(BussoundsModBlocks.LEGUERRIER, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RESIDANCE = block(BussoundsModBlocks.RESIDANCE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RENAR = block(BussoundsModBlocks.RENAR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SOURCES = block(BussoundsModBlocks.SOURCES, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ROMAINS = block(BussoundsModBlocks.ROMAINS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FEU_B = block(BussoundsModBlocks.FEU_B, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> JAN_1 = block(BussoundsModBlocks.JAN_1, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RESTAURATION = block(BussoundsModBlocks.RESTAURATION, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MARCHE = block(BussoundsModBlocks.MARCHE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> THEO = block(BussoundsModBlocks.THEO, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ROUDIN = block(BussoundsModBlocks.ROUDIN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CENTRE_ADMINISTRATIF = block(BussoundsModBlocks.CENTRE_ADMINISTRATIF, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHEMIN = block(BussoundsModBlocks.CHEMIN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DELACOUR = block(BussoundsModBlocks.DELACOUR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MANIA = block(BussoundsModBlocks.MANIA, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MAIS = block(BussoundsModBlocks.MAIS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DUCARTON = block(BussoundsModBlocks.DUCARTON, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> TUNES = block(BussoundsModBlocks.TUNES, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> HOPITAL = block(BussoundsModBlocks.HOPITAL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LAMCOMBRE = block(BussoundsModBlocks.LAMCOMBRE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LACANAILE = block(BussoundsModBlocks.LACANAILE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ANCIENNE_GARE = block(BussoundsModBlocks.ANCIENNE_GARE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CLINIQUE = block(BussoundsModBlocks.CLINIQUE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> APPARTEMENT = block(BussoundsModBlocks.APPARTEMENT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> AURELIEN = block(BussoundsModBlocks.AURELIEN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> USE = block(BussoundsModBlocks.USE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SURCOTE = block(BussoundsModBlocks.SURCOTE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PIGMENT = block(BussoundsModBlocks.PIGMENT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> POTAGE = block(BussoundsModBlocks.POTAGE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DUBOULANGE = block(BussoundsModBlocks.DUBOULANGE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ETE = block(BussoundsModBlocks.ETE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MAGASINS_USINE = block(BussoundsModBlocks.MAGASINS_USINE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CENTRE_COMMERCIAL = block(BussoundsModBlocks.CENTRE_COMMERCIAL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> THELAY = block(BussoundsModBlocks.THELAY, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> OLMAR = block(BussoundsModBlocks.OLMAR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> BOURSE = block(BussoundsModBlocks.BOURSE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LOUIS = block(BussoundsModBlocks.LOUIS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PARVI = block(BussoundsModBlocks.PARVI, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DEGANT = block(BussoundsModBlocks.DEGANT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PASSAGE = block(BussoundsModBlocks.PASSAGE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> NAGI = block(BussoundsModBlocks.NAGI, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> COEUR = block(BussoundsModBlocks.COEUR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PAIX = block(BussoundsModBlocks.PAIX, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHARB = block(BussoundsModBlocks.CHARB, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LOGE = block(BussoundsModBlocks.LOGE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> COLLEGE_ST_DEMAIN = block(BussoundsModBlocks.COLLEGE_ST_DEMAIN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> KIRO = block(BussoundsModBlocks.KIRO, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> UNIVERSITE = block(BussoundsModBlocks.UNIVERSITE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CAMPUS = block(BussoundsModBlocks.CAMPUS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ECOLES = block(BussoundsModBlocks.ECOLES, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHANTS = block(BussoundsModBlocks.CHANTS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> VERTI = block(BussoundsModBlocks.VERTI, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MARTRE = block(BussoundsModBlocks.MARTRE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LITHYA = block(BussoundsModBlocks.LITHYA, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SOLEIL = block(BussoundsModBlocks.SOLEIL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SOUSCOTE = block(BussoundsModBlocks.SOUSCOTE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ELEMENTO = block(BussoundsModBlocks.ELEMENTO, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PONTDELAUBE = block(BussoundsModBlocks.PONTDELAUBE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> BULON = block(BussoundsModBlocks.BULON, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> HABITACLE = block(BussoundsModBlocks.HABITACLE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LUEN = block(BussoundsModBlocks.LUEN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> HAKIM = block(BussoundsModBlocks.HAKIM, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SOUFFLERIE = block(BussoundsModBlocks.SOUFFLERIE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CALAMARDE = block(BussoundsModBlocks.CALAMARDE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PARC_LOGISTIQUE = block(BussoundsModBlocks.PARC_LOGISTIQUE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> TAILS = block(BussoundsModBlocks.TAILS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PONTDELAIR = block(BussoundsModBlocks.PONTDELAIR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> JARDINSDELA_GARE = block(BussoundsModBlocks.JARDINSDELA_GARE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> GARE_CENTRALE = block(BussoundsModBlocks.GARE_CENTRALE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MAIRIE = block(BussoundsModBlocks.MAIRIE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ROULONI = block(BussoundsModBlocks.ROULONI, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SEP_1 = block(BussoundsModBlocks.SEP_1, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PARSOLONA = block(BussoundsModBlocks.PARSOLONA, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SABRINA = block(BussoundsModBlocks.SABRINA, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PRES_BULON = block(BussoundsModBlocks.PRES_BULON, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> HUMBOURGEUR = block(BussoundsModBlocks.HUMBOURGEUR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> NORD = block(BussoundsModBlocks.NORD, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FIOUSE = block(BussoundsModBlocks.FIOUSE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ORIENTAL = block(BussoundsModBlocks.ORIENTAL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MONT = block(BussoundsModBlocks.MONT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHAMPSDEDAVI = block(BussoundsModBlocks.CHAMPSDEDAVI, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ARMAGEDDON = block(BussoundsModBlocks.ARMAGEDDON, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> TETEDU = block(BussoundsModBlocks.TETEDU, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MATERNEL = block(BussoundsModBlocks.MATERNEL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DEMI_CIEL = block(BussoundsModBlocks.DEMI_CIEL, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PORTEAUBOIS = block(BussoundsModBlocks.PORTEAUBOIS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHAMPONAIS = block(BussoundsModBlocks.CHAMPONAIS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MASTEUR = block(BussoundsModBlocks.MASTEUR, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> FLOCH = block(BussoundsModBlocks.FLOCH, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> LUMIERE = block(BussoundsModBlocks.LUMIERE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CHEMINEE = block(BussoundsModBlocks.CHEMINEE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> STARLESS = block(BussoundsModBlocks.STARLESS, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> TRIDENT = block(BussoundsModBlocks.TRIDENT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> BANLETA = block(BussoundsModBlocks.BANLETA, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> AN = block(BussoundsModBlocks.AN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> SAMRUTO = block(BussoundsModBlocks.SAMRUTO, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> DACHAN = block(BussoundsModBlocks.DACHAN, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> CRYTALINE = block(BussoundsModBlocks.CRYTALINE, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> KYOU = block(BussoundsModBlocks.KYOU, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> ECOLES_NT = block(BussoundsModBlocks.ECOLES_NT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> RESIDANCE_NT = block(BussoundsModBlocks.RESIDANCE_NT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> PONTDELAUBE_NT = block(BussoundsModBlocks.PONTDELAUBE_NT, BussoundsModTabs.TAB_SOUNDS);
	public static final RegistryObject<Item> MAGASINS_USINE_NT = block(BussoundsModBlocks.MAGASINS_USINE_NT, BussoundsModTabs.TAB_SOUNDS);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
